server.port=8084
spring.application.name=resilience-service
spring.cloud.gateway.routes[0].id=resilience_route
spring.cloud.gateway.routes[0].uri=http://localhost:8084
spring.cloud.gateway.routes[0].predicates[0]=Path=/slow
spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=myCircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/fallback
