server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=customer_service_route
spring.cloud.gateway.routes[0].uri=http://localhost:8085
spring.cloud.gateway.routes[0].predicates[0]=Path=/customer/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/customer/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[1].id=billing_service_route
spring.cloud.gateway.routes[1].uri=http://localhost:8086
spring.cloud.gateway.routes[1].predicates[0]=Path=/billing/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/billing/(?<segment>.*), /${segment}
