server.port=8081
spring.application.name=edge-service
spring.cloud.gateway.routes[0].id=httpbin_route
spring.cloud.gateway.routes[0].uri=https://httpbin.org
spring.cloud.gateway.routes[0].predicates[0]=Path=/get
spring.cloud.gateway.routes[1].id=local_route
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/hello
